#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'carla-walker-agent','console_scripts','carla_walker_agent'
__requires__ = 'carla-walker-agent'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('carla-walker-agent', 'console_scripts', 'carla_walker_agent')()
    )
