#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'carla-ackermann-control','console_scripts','carla_ackermann_control_node'
__requires__ = 'carla-ackermann-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('carla-ackermann-control', 'console_scripts', 'carla_ackermann_control_node')()
    )
