#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'carla-manual-control','console_scripts','carla_manual_control'
__requires__ = 'carla-manual-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('carla-manual-control', 'console_scripts', 'carla_manual_control')()
    )
